[frontend]
172.31.20.146   #course= "Ansible for node-1"
172.31.26.188   #course= "Ansible for node-2"


 [user]
 172.31.27.131



 [cart]
 172.31.27.132

# group of group children
; [roboshop:children]
; frontend
; catalogue
; user
; cart




[local]
localhost

#local group vars
[local:vars]
course= "Ansible"
trainer= "manikumar"
duration= "150HR"

[frontend:vars]
course= "Ansible"
trainer= "manikumar"
duration= "150HR"



